- 3 subt params
- 2 pf params

In [83]:
import numpy as np
import scipy as sp
from matplotlib import pyplot as plt

import pandas as pd
import seaborn as sns
import os
from statsmodels.stats.multitest import fdrcorrection
# from google.colab import drive
# drive.mount('/content/drive')

from scipy.stats import zscore

import statsmodels.api as sm

from pymer4.models import Lmer, Lm

# !pip install scikit-bio

In [84]:
# mixed_batch_data = pd.read_csv('/content/drive/MyDrive/curvefit_traits_merged_linearpf_onlyneccols.csv', index_col='subID')
mixed_batch_data = pd.read_csv('../../../data/subtlety_playfight_data/curvefit_traits_merged_linearpf_onlyneccols_fight.csv', index_col='subID')
mixed_batch_data.drop('Unnamed: 0', axis=1, inplace=True)
mixed_batch_data

,PSE_subt,range_subt,bias_subt,sigma_subt,PSE_pf,slope_pf,range_pf,bias_pf,social_skill,attn_switch,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,0.552951,0.900821,0.315504,0.103360,0.513054,0.784286,0.784286,0.452539,21.0,23.0,...,16.000000,20.0,0.0,38.0,28.000000,31.000000,34.0,39.0,56.0,3.0
30004.0,0.276896,0.805834,0.999458,0.076866,0.872907,0.469286,0.469286,0.170256,21.0,20.0,...,15.000000,25.0,11.0,38.0,26.181818,50.000000,50.0,46.0,56.0,3.0
30005.0,0.320583,0.710131,0.861730,0.115353,0.501696,0.842143,0.842143,0.490950,17.0,29.0,...,16.000000,20.0,21.0,51.0,39.000000,40.000000,43.0,19.0,41.0,5.0
30006.0,0.464823,0.989396,0.889572,0.079221,0.741046,0.674587,0.674587,0.000307,8.0,10.0,...,3.000000,25.0,0.0,18.0,41.000000,31.000000,44.0,57.0,30.0,4.0
30008.0,0.325118,0.582252,0.692710,0.172585,0.677591,0.511071,0.511071,0.314366,5.0,15.0,...,12.222222,28.0,4.0,27.0,46.000000,42.545455,46.0,50.0,45.0,5.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30344.0,0.361233,0.655715,0.794480,0.135840,0.492859,0.566786,0.566786,0.509343,27.0,18.0,...,16.000000,14.0,0.0,25.0,29.000000,49.000000,35.0,56.0,41.0,6.0
30345.0,0.475067,0.833333,1.000000,0.013915,0.639965,0.781136,0.781136,0.000457,15.0,14.0,...,5.000000,15.0,15.0,36.0,23.000000,37.000000,45.0,54.0,72.0,1.0
30346.0,0.426850,0.999914,0.961644,0.045409,0.412504,0.786429,0.786429,0.822185,16.0,25.0,...,8.000000,27.0,6.0,49.0,36.000000,36.000000,43.0,44.0,56.0,3.0
30348.0,0.729328,0.200238,0.444049,0.392303,0.468301,0.480714,0.480714,0.529344,8.0,7.0,...,2.000000,27.0,0.0,18.0,42.000000,41.000000,48.0,53.0,24.0,4.0
30352.0,0.392464,0.470243,0.528520,0.153343,0.353951,0.516786,0.516786,0.656196,8.0,6.0,...,4.000000,22.0,0.0,17.0,46.000000,47.000000,48.0,56.0,20.0,4.0

In [85]:
mixed_batch_data.isna().sum()

PSE_subt             0
range_subt           0
bias_subt            0
sigma_subt           0
PSE_pf               0
slope_pf             0
range_pf             0
bias_pf              0
social_skill         0
attn_switch          0
img                  0
attn_to_det          0
comm                 0
posAffect            0
negAffect            0
neuroticism          0
extraversion         0
openness             0
agreeableness        0
conscientiousness    0
loneliness           0
nfriends             1
dtype: int64

Looks like one subject is missing a value for `nfriends`. Let's just drop them as this will cause headaches later

In [86]:
mixed_batch_data = mixed_batch_data.dropna()
mixed_batch_data.shape

(274, 22)

In [87]:
mixed_batch_data.columns

Index(['PSE_subt', 'range_subt', 'bias_subt', 'sigma_subt', 'PSE_pf',
       'slope_pf', 'range_pf', 'bias_pf', 'social_skill', 'attn_switch', 'img',
       'attn_to_det', 'comm', 'posAffect', 'negAffect', 'neuroticism',
       'extraversion', 'openness', 'agreeableness', 'conscientiousness',
       'loneliness', 'nfriends'],
      dtype='object')

In [88]:
curve_param_cols = [
                  'PSE_subt',
                  'range_subt',
                  'bias_subt',
                  'range_pf',
                  'bias_pf'
                    ]
subt_param_cols = [
                  'PSE_subt',
                  'range_subt',
                  'bias_subt',
                   ]
pf_param_cols = [
                 'range_pf',
                 'bias_pf'
                 ]
trait_cols = [
              'social_skill', 'attn_switch', 'img', 'attn_to_det', 'comm',
              'posAffect',
              'negAffect',
              'neuroticism', 'extraversion', 'openness', 'agreeableness', 'conscientiousness',
              'loneliness',
              'nfriends'
       ]

social_cols = [
              'social_skill', 'attn_switch', 'img', 'attn_to_det', 'comm',
              'loneliness',
              'nfriends'
              ]

In [89]:
results_loc= '../../../results/subtlety_playfight_mixed/trait-beh/extra_analyses/'

In [90]:
# bias_PSE_subt = mixed_batch_data['bias_subt']/ mixed_batch_data['PSE_subt']
# bias_PSE_pf = mixed_batch_data['bias_pf']/ mixed_batch_data['PSE_pf']
# mixed_batch_data.insert(3, 'bias_PSE_subt', bias_PSE_subt)
# mixed_batch_data.insert(9, 'bias_PSE_pf', bias_PSE_pf)
# mixed_batch_data

In [91]:
# first, super important to z-score all the features in order to minimize the impact of different features being measured on different scales (just like PCA)
mixed_batch_data_zscored = mixed_batch_data.apply(zscore)
mixed_batch_data_zscored

,PSE_subt,range_subt,bias_subt,sigma_subt,PSE_pf,slope_pf,range_pf,bias_pf,social_skill,attn_switch,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,1.587100,1.139946,-2.182466,0.144545,-0.206179,0.740744,0.802900,0.052813,1.249255,1.403779,...,1.044306,-0.214096,-1.031925,0.328778,-1.032702,-1.533105,-1.890716,-0.771265,0.884033,-0.304004
30004.0,-0.836964,0.619923,1.390323,-0.452518,2.089832,-0.732085,-0.731401,-0.970100,1.249255,0.813345,...,0.862296,0.379919,0.470275,0.328778,-1.249254,1.402822,1.569992,0.078101,0.884033,-0.304004
30005.0,-0.453342,0.095984,0.670868,0.414827,-0.278646,1.011263,1.084710,0.192006,0.604630,2.584649,...,1.044306,-0.214096,1.835912,1.543459,0.277433,-0.142403,0.055932,-3.198024,-0.300924,0.449816
30006.0,0.813243,1.624863,0.816307,-0.399448,1.248505,0.227830,0.268579,-1.585944,-0.845776,-1.154772,...,-1.321823,0.379919,-1.031925,-1.539962,0.515640,-1.533105,0.272226,1.412818,-1.169892,0.072906
30008.0,-0.413524,-0.604109,-0.212045,1.704615,0.843637,-0.536710,-0.527871,-0.447886,-1.329245,-0.170714,...,0.356713,0.736328,-0.485670,-0.699029,1.111156,0.250927,0.704815,0.563453,0.015065,0.449816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30344.0,-0.096389,-0.201924,0.319575,0.876526,-0.335034,-0.276210,-0.256498,0.258657,2.216193,0.419721,...,1.044306,-0.926914,-1.031925,-0.885903,-0.913599,1.248300,-1.674422,1.291480,-0.300924,0.826726
30345.0,0.903194,0.770473,1.393153,-1.871185,0.603566,0.726018,0.787560,-1.585402,0.282318,-0.367525,...,-0.957803,-0.808111,1.016530,0.141904,-1.628218,-0.605970,0.488521,1.048804,2.147987,-1.057824
30346.0,0.479799,1.682444,1.192794,-1.161440,-0.847731,0.750763,0.813338,1.392306,0.443474,1.797403,...,-0.411773,0.617525,-0.212543,1.356585,-0.079876,-0.760493,0.055932,-0.164575,0.884033,-0.304004
30348.0,3.135886,-2.695502,-1.510981,6.656212,-0.491721,-0.678649,-0.675735,0.331135,-0.845776,-1.745207,...,-1.503832,0.617525,-1.031925,-1.539962,0.634743,0.012120,1.137403,0.927466,-1.643875,0.072906
30352.0,0.177852,-1.217317,-1.069726,1.270978,-1.221324,-0.509992,-0.500038,0.790810,-0.845776,-1.942019,...,-1.139813,0.023510,-1.031925,-1.633399,1.111156,0.939255,1.137403,1.291480,-1.959863,0.072906

In [92]:
mixed_batch_data['PSE_subt'].describe()

count    274.000000
mean       0.372210
std        0.114089
min        0.000000
25%        0.327620
50%        0.387369
75%        0.444022
max        0.729328
Name: PSE_subt, dtype: float64

In [93]:
bias_PSE_subt = mixed_batch_data_zscored['bias_subt']/ mixed_batch_data_zscored['PSE_subt']
bias_PSE_pf = mixed_batch_data_zscored['bias_pf']/ mixed_batch_data_zscored['PSE_pf']

bias_PSE_subt_diff = mixed_batch_data_zscored['bias_subt'] - mixed_batch_data_zscored['PSE_subt']
bias_PSE_pf_diff = mixed_batch_data_zscored['bias_pf'] - mixed_batch_data_zscored['PSE_pf']

# bias_PSE_subt = zscore(mixed_batch_data_zscored['bias_subt']/ mixed_batch_data_zscored['PSE_subt'])
# bias_PSE_pf = zscore(mixed_batch_data_zscored['bias_pf']/ mixed_batch_data_zscored['PSE_pf'])

mixed_batch_data_zscored.insert(3, 'bias_PSE_subt', bias_PSE_subt)
mixed_batch_data_zscored.insert(4, 'bias_PSE_subt_diff', bias_PSE_subt_diff)
mixed_batch_data_zscored.insert(9, 'bias_PSE_pf', bias_PSE_pf)
mixed_batch_data_zscored.insert(10, 'bias_PSE_pf_diff', bias_PSE_pf_diff)
mixed_batch_data_zscored

,PSE_subt,range_subt,bias_subt,bias_PSE_subt,bias_PSE_subt_diff,sigma_subt,PSE_pf,slope_pf,range_pf,bias_PSE_pf,...,comm,posAffect,negAffect,neuroticism,extraversion,openness,agreeableness,conscientiousness,loneliness,nfriends
subID,,,,,,,,,,,,,,,,,,,,,
30002.0,1.587100,1.139946,-2.182466,-1.375128,-3.769566,0.144545,-0.206179,0.740744,0.802900,-0.256151,...,1.044306,-0.214096,-1.031925,0.328778,-1.032702,-1.533105,-1.890716,-0.771265,0.884033,-0.304004
30004.0,-0.836964,0.619923,1.390323,-1.661150,2.227287,-0.452518,2.089832,-0.732085,-0.731401,-0.464200,...,0.862296,0.379919,0.470275,0.328778,-1.249254,1.402822,1.569992,0.078101,0.884033,-0.304004
30005.0,-0.453342,0.095984,0.670868,-1.479827,1.124210,0.414827,-0.278646,1.011263,1.084710,-0.689067,...,1.044306,-0.214096,1.835912,1.543459,0.277433,-0.142403,0.055932,-3.198024,-0.300924,0.449816
30006.0,0.813243,1.624863,0.816307,1.003768,0.003064,-0.399448,1.248505,0.227830,0.268579,-1.270275,...,-1.321823,0.379919,-1.031925,-1.539962,0.515640,-1.533105,0.272226,1.412818,-1.169892,0.072906
30008.0,-0.413524,-0.604109,-0.212045,0.512777,0.201478,1.704615,0.843637,-0.536710,-0.527871,-0.530899,...,0.356713,0.736328,-0.485670,-0.699029,1.111156,0.250927,0.704815,0.563453,0.015065,0.449816
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
30344.0,-0.096389,-0.201924,0.319575,-3.315470,0.415964,0.876526,-0.335034,-0.276210,-0.256498,-0.772031,...,1.044306,-0.926914,-1.031925,-0.885903,-0.913599,1.248300,-1.674422,1.291480,-0.300924,0.826726
30345.0,0.903194,0.770473,1.393153,1.542475,0.489960,-1.871185,0.603566,0.726018,0.787560,-2.626725,...,-0.957803,-0.808111,1.016530,0.141904,-1.628218,-0.605970,0.488521,1.048804,2.147987,-1.057824
30346.0,0.479799,1.682444,1.192794,2.486030,0.712995,-1.161440,-0.847731,0.750763,0.813338,-1.642392,...,-0.411773,0.617525,-0.212543,1.356585,-0.079876,-0.760493,0.055932,-0.164575,0.884033,-0.304004
30348.0,3.135886,-2.695502,-1.510981,-0.481835,-4.646867,6.656212,-0.491721,-0.678649,-0.675735,-0.673421,...,-1.503832,0.617525,-1.031925,-1.539962,0.634743,0.012120,1.137403,0.927466,-1.643875,0.072906
30352.0,0.177852,-1.217317,-1.069726,-6.014703,-1.247577,1.270978,-1.221324,-0.509992,-0.500038,-0.647502,...,-1.139813,0.023510,-1.031925,-1.633399,1.111156,0.939255,1.137403,1.291480,-1.959863,0.072906

# predict curve fit params from all traits

In [94]:
trait_cols

['social_skill',
 'attn_switch',
 'img',
 'attn_to_det',
 'comm',
 'posAffect',
 'negAffect',
 'neuroticism',
 'extraversion',
 'openness',
 'agreeableness',
 'conscientiousness',
 'loneliness',
 'nfriends']

In [95]:
param_list = ['bias_PSE_subt','bias_PSE_subt_diff','bias_subt','PSE_subt']

all_ps = np.full((len(trait_cols),len(param_list)),np.nan) # for MCC
for iparam,param in enumerate(param_list):
    print(f'\nPARAM {param}')
    model = Lm(f"{param} ~ social_skill + attn_switch + img + attn_to_det + comm + posAffect + negAffect + neuroticism + extraversion + openness + agreeableness + conscientiousness + loneliness + nfriends", data=mixed_batch_data_zscored)
    print(model.fit())
    for t,trait in enumerate(trait_cols): # for MCC
        all_ps[t, iparam] = model.coefs['P-val'][trait]

PARAM bias_PSE_subt
Formula: bias_PSE_subt~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.032	 R^2_adj: -0.020

Log-likelihood: -1480.622 	 AIC: 2991.244	 BIC: 3045.441

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -4.088 -10.667    2.492  3.341  259  -1.223  0.222
social_skill          1.879 -12.936   16.694  7.524  259   0.250  0.803
attn_switch           2.567  -7.616   12.749  5.171  259   0.496  0.620
img                  -1.094  -9.577    7.389  4.308  259  -0.254  0.800
attn_to_det          -2.196  -9.710    5.318  3.816  259  -0.575  0.566
comm                 -1.060 -13.261   11.140  6.196  259  -0.171  0.864
posAffect            -0.258 -10.651   10.134  5.278  259  -0.049  0.961
negAffect            -0.038  -9.742    9.666  4.928  259  -0.008  0.994
neuroticism           8.057  -4.415   20.529  6.334  259   1.272  0.204
extraversion          2.371 -10.845   15.587  6.712  259   0.353  0.724
openness              5.387  -2.001   12.775  3.752  259   1.436  0.152
agreeableness        -5.805 -14.506    2.895  4.419  259  -1.314  0.190
conscientiousness     1.643  -7.441   10.727  4.613  259   0.356  0.722
loneliness           -8.113 -18.694    2.468  5.373  259  -1.510  0.132
nfriends              1.473  -6.167    9.114  3.880  259   0.380  0.704

PARAM bias_PSE_subt_diff
Formula: bias_PSE_subt_diff~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.091	 R^2_adj: 0.041

Log-likelihood: -520.759 	 AIC: 1071.518	 BIC: 1125.715

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept             0.000  -0.198    0.198  0.101  259   0.000  1.000
social_skill          0.094  -0.352    0.540  0.226  259   0.414  0.679
attn_switch           0.258  -0.049    0.564  0.156  259   1.657  0.099   .
img                   0.138  -0.117    0.394  0.130  259   1.067  0.287
attn_to_det           0.036  -0.190    0.262  0.115  259   0.314  0.754
comm                 -0.532  -0.900   -0.165  0.187  259  -2.854  0.005  **
posAffect            -0.001  -0.314    0.312  0.159  259  -0.008  0.993
negAffect            -0.009  -0.301    0.283  0.148  259  -0.061  0.951
neuroticism           0.234  -0.141    0.610  0.191  259   1.229  0.220
extraversion          0.388  -0.009    0.786  0.202  259   1.923  0.056   .
openness              0.115  -0.107    0.337  0.113  259   1.018  0.310
agreeableness        -0.375  -0.637   -0.114  0.133  259  -2.823  0.005  **
conscientiousness     0.161  -0.112    0.434  0.139  259   1.159  0.247
loneliness            0.014  -0.305    0.332  0.162  259   0.086  0.932
nfriends              0.061  -0.169    0.291  0.117  259   0.521  0.603

PARAM bias_subt
Formula: bias_subt~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.089	 R^2_adj: 0.040

Log-likelihood: -376.040 	 AIC: 782.080	 BIC: 836.277

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -0.000  -0.117    0.117  0.059  259  -0.000  1.000
social_skill         -0.020  -0.283    0.243  0.134  259  -0.148  0.882
attn_switch           0.201   0.020    0.382  0.092  259   2.191  0.029   *
img                   0.085  -0.066    0.236  0.076  259   1.112  0.267
attn_to_det           0.005  -0.129    0.138  0.068  259   0.068  0.946
comm                 -0.331  -0.548   -0.115  0.110  259  -3.012  0.003  **
posAffect            -0.038  -0.223    0.146  0.094  259  -0.407  0.684
negAffect             0.085  -0.087    0.257  0.087  259   0.971  0.333
neuroticism           0.118  -0.103    0.340  0.112  259   1.053  0.293
extraversion          0.110  -0.125    0.345  0.119  259   0.924  0.356
openness              0.073  -0.058    0.204  0.067  259   1.092  0.276
agreeableness        -0.154  -0.309    0.000  0.078  259  -1.965  0.051   .
conscientiousness     0.175   0.014    0.336  0.082  259   2.136  0.034   *
loneliness           -0.029  -0.217    0.158  0.095  259  -0.309  0.758
nfriends              0.024  -0.111    0.160  0.069  259   0.351  0.726

PARAM PSE_subt
Formula: PSE_subt~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.073	 R^2_adj: 0.023

Log-likelihood: -378.400 	 AIC: 786.801	 BIC: 840.997

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -0.000  -0.118    0.118  0.060  259  -0.000  1.000
social_skill         -0.113  -0.379    0.152  0.135  259  -0.842  0.400
attn_switch          -0.057  -0.239    0.125  0.093  259  -0.614  0.540
img                  -0.053  -0.205    0.099  0.077  259  -0.691  0.490
attn_to_det          -0.031  -0.166    0.103  0.068  259  -0.460  0.646
comm                  0.201  -0.017    0.419  0.111  259   1.812  0.071   .
posAffect            -0.037  -0.223    0.149  0.094  259  -0.390  0.697
negAffect             0.094  -0.080    0.268  0.088  259   1.065  0.288
neuroticism          -0.116  -0.339    0.107  0.113  259  -1.022  0.308
extraversion         -0.278  -0.515   -0.042  0.120  259  -2.316  0.021   *
openness             -0.042  -0.175    0.090  0.067  259  -0.629  0.530
agreeableness         0.221   0.066    0.377  0.079  259   2.798  0.006  **
conscientiousness     0.014  -0.149    0.177  0.083  259   0.168  0.866
loneliness           -0.043  -0.233    0.146  0.096  259  -0.450  0.653
nfriends             -0.037  -0.174    0.100  0.069  259  -0.529  0.597

In [96]:
param_list = ['bias_PSE_pf','bias_PSE_pf_diff', 'bias_pf','PSE_pf']

all_ps = np.full((len(trait_cols),len(param_list)),np.nan) # for MCC
for iparam,param in enumerate(param_list):
    print(f'\nPARAM {param}')
    model = Lm(f"{param} ~ social_skill + attn_switch + img + attn_to_det + comm + posAffect + negAffect + neuroticism + extraversion + openness + agreeableness + conscientiousness + loneliness + nfriends", data=mixed_batch_data_zscored)
    print(model.fit())
    for t,trait in enumerate(trait_cols): # for MCC
        all_ps[t, iparam] = model.coefs['P-val'][trait]

PARAM bias_PSE_pf
Formula: bias_PSE_pf~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.085	 R^2_adj: 0.036

Log-likelihood: -1284.816 	 AIC: 2599.633	 BIC: 2653.830

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -2.413  -5.633    0.807  1.635  259  -1.476  0.141
social_skill         -0.452  -7.702    6.798  3.682  259  -0.123  0.902
attn_switch          -1.808  -6.791    3.175  2.531  259  -0.715  0.476
img                  -2.536  -6.687    1.616  2.108  259  -1.203  0.230
attn_to_det           0.633  -3.044    4.311  1.867  259   0.339  0.735
comm                  3.772  -2.199    9.742  3.032  259   1.244  0.215
posAffect             0.778  -4.308    5.864  2.583  259   0.301  0.763
negAffect             4.268  -0.481    9.017  2.412  259   1.770  0.078   .
neuroticism          -5.960 -12.064    0.143  3.100  259  -1.923  0.056   .
extraversion          2.594  -3.874    9.062  3.284  259   0.790  0.430
openness              4.832   1.216    8.447  1.836  259   2.632  0.009  **
agreeableness        -2.200  -6.458    2.058  2.162  259  -1.017  0.310
conscientiousness    -0.367  -4.812    4.079  2.258  259  -0.162  0.871
loneliness           -0.208  -5.386    4.971  2.630  259  -0.079  0.937
nfriends             -1.761  -5.500    1.978  1.899  259  -0.927  0.355

PARAM bias_PSE_pf_diff
Formula: bias_PSE_pf_diff~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.049	 R^2_adj: -0.002

Log-likelihood: -549.454 	 AIC: 1128.907	 BIC: 1183.104

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept             0.000  -0.220    0.220  0.112  259   0.000  1.000
social_skill         -0.019  -0.515    0.476  0.251  259  -0.077  0.939
attn_switch           0.020  -0.320    0.361  0.173  259   0.117  0.907
img                  -0.022  -0.306    0.261  0.144  259  -0.155  0.877
attn_to_det           0.134  -0.117    0.385  0.128  259   1.049  0.295
comm                 -0.114  -0.522    0.294  0.207  259  -0.550  0.583
posAffect            -0.086  -0.433    0.262  0.176  259  -0.485  0.628
negAffect             0.146  -0.178    0.470  0.165  259   0.887  0.376
neuroticism           0.023  -0.393    0.440  0.212  259   0.111  0.912
extraversion         -0.230  -0.672    0.211  0.224  259  -1.026  0.306
openness             -0.162  -0.409    0.085  0.125  259  -1.293  0.197
agreeableness        -0.191  -0.482    0.099  0.148  259  -1.296  0.196
conscientiousness     0.014  -0.289    0.318  0.154  259   0.093  0.926
loneliness           -0.453  -0.807   -0.100  0.180  259  -2.524  0.012   *
nfriends              0.104  -0.151    0.360  0.130  259   0.805  0.422

PARAM bias_pf
Formula: bias_pf~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.055	 R^2_adj: 0.003

Log-likelihood: -381.103 	 AIC: 792.206	 BIC: 846.403

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -0.000  -0.119    0.119  0.060  259  -0.000  1.000
social_skill         -0.025  -0.293    0.243  0.136  259  -0.182  0.856
attn_switch           0.038  -0.146    0.222  0.094  259   0.408  0.684
img                   0.018  -0.136    0.171  0.078  259   0.229  0.819
attn_to_det           0.099  -0.037    0.235  0.069  259   1.440  0.151
comm                 -0.025  -0.245    0.196  0.112  259  -0.221  0.825
posAffect            -0.076  -0.264    0.112  0.095  259  -0.797  0.426
negAffect             0.097  -0.079    0.272  0.089  259   1.083  0.280
neuroticism          -0.023  -0.248    0.203  0.115  259  -0.197  0.844
extraversion         -0.097  -0.336    0.142  0.121  259  -0.797  0.426
openness             -0.066  -0.199    0.068  0.068  259  -0.966  0.335
agreeableness        -0.098  -0.255    0.060  0.080  259  -1.223  0.222
conscientiousness     0.010  -0.154    0.175  0.083  259   0.126  0.900
loneliness           -0.222  -0.413   -0.030  0.097  259  -2.282  0.023   *
nfriends              0.096  -0.042    0.234  0.070  259   1.365  0.173

PARAM PSE_pf
Formula: PSE_pf~social_skill+attn_switch+img+attn_to_det+comm+posAffect+negAffect+neuroticism+extraversion+openness+agreeableness+conscientiousness+loneliness+nfriends

Family: gaussian	 Estimator: OLS

Std-errors: non-robust	CIs: standard 95%	Inference: parametric

Number of observations: 274	 R^2: 0.043	 R^2_adj: -0.009

Log-likelihood: -382.820 	 AIC: 795.640	 BIC: 849.836

Fixed effects:

                   Estimate  2.5_ci  97.5_ci     SE   DF  T-stat  P-val Sig
Intercept            -0.000  -0.120    0.120  0.061  259  -0.000  1.000
social_skill         -0.005  -0.275    0.264  0.137  259  -0.040  0.968
attn_switch           0.018  -0.167    0.203  0.094  259   0.190  0.849
img                   0.040  -0.114    0.194  0.078  259   0.511  0.610
attn_to_det          -0.034  -0.171    0.102  0.069  259  -0.496  0.620
comm                  0.089  -0.133    0.311  0.113  259   0.790  0.430
posAffect             0.009  -0.180    0.199  0.096  259   0.099  0.921
negAffect            -0.050  -0.226    0.127  0.090  259  -0.552  0.581
neuroticism          -0.046  -0.273    0.181  0.115  259  -0.400  0.690
extraversion          0.134  -0.107    0.374  0.122  259   1.093  0.275
openness              0.097  -0.038    0.231  0.068  259   1.415  0.158
agreeableness         0.094  -0.065    0.252  0.080  259   1.165  0.245
conscientiousness    -0.004  -0.169    0.161  0.084  259  -0.046  0.963
loneliness            0.232   0.039    0.424  0.098  259   2.369  0.019   *
nfriends             -0.009  -0.148    0.130  0.071  259  -0.122  0.903

In [66]:
result_bool = np.full_like(all_ps,np.nan)
corrected_p = np.full_like(all_ps,np.nan)
for t, trait in enumerate(trait_cols): # MCC one PC at a time
    result_bool[t,:], corrected_p[t,:] = fdrcorrection(all_ps[t,:]) # MCC across all params for one PC (regressor) at a time
    print(trait, np.where(result_bool[t,:])[0], np.array(param_list)[np.where(result_bool[t,:])[0]])

social_skill [] []
attn_switch [] []
img [] []
attn_to_det [] []
comm [] []
posAffect [] []
negAffect [] []
neuroticism [] []
extraversion [] []
openness [0] ['bias_PSE_pf']
agreeableness [] []
conscientiousness [] []
loneliness [1 2] ['bias_pf' 'PSE_pf']
nfriends [] []

In [109]:
from scipy import stats

In [110]:
x = mixed_batch_data_zscored['comm']
y = mixed_batch_data_zscored['bias_subt']
stats.pearsonr(x,y)

PearsonRResult(statistic=np.float64(-0.12728067802299373), pvalue=np.float64(0.03522083935901831))

In [113]:
x = mixed_batch_data_zscored['agreeableness']
y = mixed_batch_data_zscored['PSE_subt']
stats.pearsonr(x,y)

PearsonRResult(statistic=np.float64(0.0921577530255825), pvalue=np.float64(0.1280721402383504))