- script to get actual N's for all studies

In [7]:
import pandas as pd
import numpy as np

# I. Text

## 1. subtlety

In [8]:
pwd

'/Users/f0053cz/Dartmouth College Dropbox/Rekha Sreekumar Varrier/postdoc_Dartmouth/psyanim_behav_paper/version2/scripts_data_for_beh_paper/code'

In [9]:
expt_type = 'subtlety/without_cover_story/'
rootfile_loc = f'../data/text_responses/{expt_type}'
df =  pd.read_csv(f'{rootfile_loc}/data_triallevel_sorted.csv',index_col=[0])
df.head()

,subID,stimset_rows,subtlety,responses,movie,trial_num
0,15000,0,0,grey dot following black dot,07cdb9d7-6577-428d-9498-8a7243527554,0
6,15001,1,0,A grey dot appeared to chase or follow a black...,53613c0d-b07e-4b22-b6ec-56dda26edc8f,6
0,15002,2,0,the black dot seemed to be running away from t...,19c65966-3d88-4851-afe4-ae34c498748c,0
2,15003,3,0,Black dot was following the grey dot,c188e383-94d7-475e-9da5-6d1f0a1184bb,2
3,15004,6,0,Black moved from right to left chasing the grey,49e5ac90-6e7f-4243-9552-8c4c10545895,3

In [11]:
len(np.unique(df['subID']))

60

## 2. playfight

### without cover story

In [14]:
expt_type = 'playfight/without_cover_story/'
rootfile_loc = f'../data/text_responses/{expt_type}'

In [15]:
df =  pd.read_csv(f'{rootfile_loc}/data_triallevel_sorted.csv',index_col=[0])
df.head()

,subID,stimset_rows,chargeSpeed,stim_dur,responses,movie,trial_num
1,28000,26,1.5,8234,collided and then bounced off each other,29e7c94f-a6bf-4f1d-8ea1-46efbdb6a836,1
1,28001,25,1.5,8130,"The dots moved apart, and then came back toget...",e838dadb-c02f-4273-ae93-210720dcd06c,1
3,28002,28,1.5,8325,softy hit twice,b3a507ff-2289-4ad3-8922-1a3d0532e154,3
6,28003,29,1.5,8085,The dots wandered and came together almost inc...,1b1159fc-de2b-4ae5-a736-d98d8524a366,6
4,28004,32,1.5,8069,softer collisons,1f6c6525-a740-48c2-8dfc-9c4fb520c630,4

In [16]:
len(np.unique(df['subID']))

103

### with cover story

In [17]:
expt_type = 'playfight/with_cover_story/'
rootfile_loc = f'../data/text_responses/{expt_type}'

In [18]:
df =  pd.read_csv(f'{rootfile_loc}/data_triallevel_sorted.csv',index_col=[0])
df.head()

,subID,stimset_rows,chargeSpeeds,responses,movie,trial_num
6,24093,10,1.5,They are peaceful,29e7c94f-a6bf-4f1d-8ea1-46efbdb6a836,6
6,24066,59,1.5,Slowly coming together to bump each other.,1a8cf3c1-690b-449c-bb36-fd3b251837c1,6
6,24067,90,1.5,Bumping into each other,e838dadb-c02f-4273-ae93-210720dcd06c,6
5,24068,57,1.5,They are kicking a ball.,31e1789e-459a-4f3d-bfdd-2f4c8c4e9f50,5
4,24069,42,1.5,playing frisbee,8ed7c0fc-1490-4e35-a000-7f7357a0772a,4

In [19]:
len(np.unique(df['subID']))

102

# II. Ratings

## 1. Subtlety

### Mainv

In [22]:
# root_file = '/Users/f0053cz/Documents/psyanim_v2/subtlety/subtlety_v2_data_Zishan/data/old_data/all_'
root_file = '../data/subtlety_data/all_'
batch_name = 'apr_ses1'
# df = pd.read_csv('../data/all_dec_ses1.csv',index_col=[0])
df = pd.read_csv(f'{root_file}{batch_name}.csv')#,index_col=[0])
df.head()

,stim_file,condition,subtlety,pred_color,slider,button_response,RT,accuracy,subID,trial_ind
0,c53236a2-f564-41ec-89aa-2bd90765b0a4,chase,30,black,100.0,black,3.065,1,1,0
1,75182d69-6502-4d35-9298-e331061c7829,chase,0,grey,100.0,grey,4.618,1,1,1
2,31932267-3908-4599-ba56-ba5043757838,chase,30,grey,100.0,grey,3.330,1,1,2
3,57dbdc86-9c49-4214-a908-c4a254e90229,chase,30,grey,100.0,grey,3.935,1,1,3
4,6480385b-e9eb-45a9-88e3-aade6c90476d,chase,120,black,70.0,black,4.133,1,1,4

In [23]:
len(np.unique(df['subID']))

312

### ses 2

In [43]:
sesID=2
df = pd.read_csv(f'../data/subtlety_data/all_apr_ses{sesID}.csv',index_col=[0]) 
df.head()

,condition,subtlety,slider,RT,accuracy,subID,trial_ind
stim_file,,,,,,,
7d329546-ecf4-4612-8f00-c127c77d5d6c,chase,60,100.0,2.264,1,265,0
68be0cf8-ea92-4566-b84a-cbd60b2e5547,wander,180,19.0,3.469,1,265,1
884bc951-67a6-42bd-8ea7-ece0c8745d3f,chase,0,100.0,2.826,1,265,2
24724e9a-8a79-4ab8-a58f-e007c5d00714,chase,120,95.0,3.256,1,265,3
cd9d4d31-b57e-4c3d-86c6-267ce9eec948,chase,60,100.0,2.497,1,265,4

In [44]:
len(np.unique(df['subID']))

240

### with mimic v

In [58]:
sesID=1
# root_file = '/Users/f0053cz/Documents/psyanim_v2/subtlety/subtlety_v2_data_Zishan/data/raw_data_'
root_file = f'../data/subtlety_data/Dec_withmimic/dec_ses{sesID}/all_'
batch_name = f'dec_ses{sesID}'
df = pd.read_csv(f'{root_file}{batch_name}.csv')#,index_col=[0])
df.head()

,stim_file,condition,subtlety,slider,RT,accuracy,subID,trial_ind
0,4c50352d-2e1e-4e2e-ad43-613002422011,mimic,90,0.0,3.395,1,1,0
1,c53236a2-f564-41ec-89aa-2bd90765b0a4,chase,30,76.0,3.437,1,1,1
2,5dbc75c6-6973-4ae1-aaf0-d3b84feb4723,wander,180,0.0,4.565,0,1,2
3,65ae3786-93f4-4878-bcfe-7cee118774dc,mimic,0,3.0,4.251,1,1,3
4,91659665-5079-44c4-96c1-49da784170fa,chase,60,78.0,3.606,1,1,4

In [59]:
len(np.unique(df['subID']))

308

### ses2

In [56]:
sesID=2
root_file = f'../data/subtlety_data/Dec_withmimic/dec_ses{sesID}/all_'
batch_name = f'dec_ses{sesID}'
df = pd.read_csv(f'{root_file}{batch_name}.csv')#,index_col=[0])
df.head()

,stim_file,condition,subtlety,pred_color,slider,button_response,RT,accuracy,subID,trial_ind
0,7bee52f4-919b-4633-b742-a0181f5f7f01,wander,180,grey,25.0,grey,2.580,1,172,0
1,2f9adc31-096c-49c5-ad0e-45cea6c1a263,mimic,120,black,37.0,black,1.892,1,172,1
2,ab00d160-e81d-4e88-8498-f20c2da7c451,mimic,60,grey,9.0,black,2.838,0,172,2
3,4a6f7598-dc16-47d6-987e-a48c1f938428,wander,180,grey,30.0,black,2.928,0,172,3
4,7d6cad69-203a-49a4-9c6e-b0423a669e50,chase,90,grey,69.0,grey,2.006,1,172,4

In [57]:
len(np.unique(df['subID']))

224

# playfight

In [60]:
sesID = 1
root_file = '../data/playfight_data/'
batch_name = f'final_data_triallevel_sorted_ses{sesID}'
df = pd.read_csv(f'{root_file}{batch_name}.csv',index_col=[0])
df.head()

,subID,stimset_rows,chargeSpeeds,stim_dur,responses,RT,movie,trial_num
8,26000,266,1.5,7761,13.0,1.51,e838dadb-c02f-4273-ae93-210720dcd06c,8
12,26000,266,1.5,7706,2.0,1.68,1f6c6525-a740-48c2-8dfc-9c4fb520c630,12
15,26000,266,1.5,7684,4.0,1.77,9d425f58-501f-43f3-955e-05126bd09bb5,15
16,26000,266,1.5,7672,2.0,1.53,1b1159fc-de2b-4ae5-a736-d98d8524a366,16
18,26000,266,1.5,7769,9.0,4.41,d3cc8306-21ab-4f88-ae4f-3970e4cd53ea,18

In [61]:
len(np.unique(df['subID']))

319

### ses2

In [62]:
sesID = 2
root_file = '../data/playfight_data/'
batch_name = f'final_data_triallevel_sorted_ses{sesID}'
df = pd.read_csv(f'{root_file}{batch_name}.csv',index_col=[0])
df.head()

,subID,stimset_rows,chargeSpeeds,stim_dur,responses,RT,movie,trial_num
18,26000,NaN,1.5,7934,0.0,4.41,95aaf072-b6be-4da4-9857-deaf20ab49f2,18
22,26000,NaN,1.5,7961,6.0,1.61,38ad4b16-44e2-4e52-8d02-b23eca73a48d,22
25,26000,NaN,1.5,7883,6.0,2.75,15dfbaca-4429-4c18-90f4-8d4804129e6f,25
28,26000,NaN,1.5,7939,16.0,3.73,e4bc0778-6eb7-4065-bf77-a9b6e293735f,28
32,26000,NaN,1.5,7921,14.0,2.94,7e595f18-f375-4ca5-b922-61b8d693804d,32

In [63]:
len(np.unique(df['subID']))

269

# 3. Mixed batch

In [33]:
df = pd.read_csv('../data/subtlety_playfight_data/subtlety_data.csv',index_col=[0])
df.head()

,subID,block_type,subtlety,chargeSpeeds,responses_subt_1,responses_subt_2,pred_color,responses_pf,RT,movie,trial_num,stim_dur,subt_norm,chargeSpeed_norm,accuracy,responses_pf_rev,chargeSpeed_norm_rev
14,30002,1,90.0,NaN,82.0,grey,grey,NaN,2002.0,06f1dd04-cfbc-433c-9833-32cdb01c0683,14,5692,0.500000,NaN,1.0,NaN,NaN
15,30002,1,30.0,NaN,91.0,grey,grey,NaN,1484.0,57dbdc86-9c49-4214-a908-c4a254e90229,15,5658,0.833333,NaN,1.0,NaN,NaN
16,30002,1,60.0,NaN,79.0,grey,grey,NaN,1774.0,3273fde2-4b65-4cc7-b9b3-ef2604e8a514,16,5645,0.666667,NaN,1.0,NaN,NaN
17,30002,1,90.0,NaN,28.0,black,black,NaN,2049.0,89ce6bb6-b2cb-44cb-ba57-d78ab0224625,17,5669,0.500000,NaN,1.0,NaN,NaN
18,30002,1,90.0,NaN,40.0,grey,grey,NaN,1616.0,7d6cad69-203a-49a4-9c6e-b0423a669e50,18,5620,0.500000,NaN,1.0,NaN,NaN

In [34]:
len(np.unique(df['subID']))

279

In [37]:
df = pd.read_csv('../data/subtlety_playfight_data/playfight_data.csv',index_col=[0])
len(np.unique(df['subID']))

279